### ISSUE TITLE
IMU - Not All Values Output/Update

### ISSUE THREAD

**Issue by E3t1jump** [Engineering-3/RCM-BFin#5]
At times, after running the IMU activation code (see below), not all IMU values are updating. Even after physically removing all sensors and motors from the RCMx1 other than the IMU, and deactivating all sensor reads from MainController other than the IMU reads (roll, pitch, heading); there we still episodes of one of the values not activating after loading/running the IMU activation code (most often, Pitch).

Not sure if this is a firmware or sensor issue. I've swapped in/out IMU sensor boards and it happens from one to the next.

writei2c(0x28, 0x3D, 0x0C);
delay(20);

**Comment by E3t1jump** [comment]
After further testing, this may be related to MainController and/or the I2C streaming???

I'm running MC 5.3.2; test 62 firmware. I have the following sensor configs active.

Numeric 6
Heading, Analog, 28, 1B, V/16
Signed
Streaming, 250

Numeric 7
Roll, Analog, 28, 1D, V/16
Signed
Streaming, 250

Numeric 8
Pitch, Analog, 28, 1F, V/16
Signed
Streaming, 250

Before running the code, all values read as 0.

I loaded/ran the code:

writei2c(0x28, 0x3D, 0x0C);
delay(20);

Heading and Roll running; Pitch reads 0 and not updating.

I went into the Sensor Config of MainController and reset as follows:

Numeric 6
Pitch, Analog, 28, 1F, V/16
Signed
Streaming, 250

Numeric 8
Heading, Analog, 28, 1B, V/16
Signed
Streaming, 250

And ALL now reading/updating.

**Comment by EmbeddedMan** [comment]
What is the exact sensor setup you are using to attempt to read out all of the IMU values?

In addition, what happens when it doesn't work? Do you just get zeros for the registers that aren't working? (i.e. pitch)

**Comment by EmbeddedMan** [comment]
And, very nice. That's the info I need. Thanks-

**Comment by E3t1jump** [comment]
I kept the settings with Pitch on Numeric 6 and Heading on Numeric 8 and repeated the start-up steps as above from a fresh power on.

Now Heading is reading 0 and not updating.

So, third one in the sequence seems to not activate.

**Comment by E3t1jump** [comment]
As an alternate test, I added a new SensorConfig:

Numeric 2
Heading, Analog, 28, 1B, V/16
Signed
Streaming, 250

This puts the MC order at:

Numeric 2 - Heading
Numeric 6 - Pitch
Numeric 7 - Roll
Numeric 8 - Heading

Now it is Roll that reads 0 and no updates. Both Headings update.

**Comment by EmbeddedMan** [comment]
I have confirmed your findings - I get the same behavior. I'm 99% confident this is a MC issue and not a firmware issue. I think it has to do with MC tracking what sensors are enabled and which are disabled.

For example, when I enable 3 sensors (say heading, pitch and roll) at once, and I'm getting 0 for the roll, it's because MC has only told the firmware to stream heading and pitch. In other words, there are only 2 I2C reads every 250ms, not 3 like there should be.

If you enable the sensors one at a time (i.e. start with none enabled, then turn on one at a time, existing from the sensors config window each time) it appears to work correctly - I then get 3 I2C reads every 250ms and all 3 values are updating properly.

If I then disable all 3 sensors, MC does not actually turn all 3 streaming commands off! Instead, I still get one I2C read (to heading in my case) every 250ms, even though all sensors are disabled.

So the problem appears to be with how MC keeps track of what sensors are on/off, and what have changed as you enable/disable them in the sensors config window. It doesn't send the right number of streaming enable/disable commands to the Bfin whenever there is a change to the sensors config window.

You can open a new issue in the MC repo and refer to this issue from there so that all of this history is trackable through that issue.

**Comment by E3t1jump** [comment]
Re-posting this issue to MainController.
